import { MigrationInterface, QueryRunner } from "typeorm";

export class HardHoldModel1783084797031 implements MigrationInterface {
    name = 'HardHoldModel1783084797031'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "Idx_reserve_status"`);
        await queryRunner.query(`DROP INDEX "Idx_reserve_user_ticket"`);
        await queryRunner.query(`DROP INDEX "Idx_reserve_ticket_id"`);
        await queryRunner.query(`CREATE TABLE "temporary_reserve" ("id" varchar PRIMARY KEY NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "status" text NOT NULL DEFAULT ('pending'), "expiresAt" datetime NOT NULL, "userId" varchar, "ticketId" varchar, CONSTRAINT "FK_dc318c87bc1d6552424a88a6444" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_reserve"("id", "createdAt", "updatedAt", "status", "expiresAt", "userId", "ticketId") SELECT "id", "createdAt", "updatedAt", "status", "expiresAt", "userId", "ticketId" FROM "reserve"`);
        await queryRunner.query(`DROP TABLE "reserve"`);
        await queryRunner.query(`ALTER TABLE "temporary_reserve" RENAME TO "reserve"`);
        await queryRunner.query(`CREATE INDEX "Idx_reserve_status" ON "reserve" ("status", "expiresAt") WHERE status = 'pending'`);
        await queryRunner.query(`CREATE INDEX "Idx_reserve_user_ticket" ON "reserve" ("userId", "ticketId") WHERE status = 'pending'`);
        await queryRunner.query(`CREATE INDEX "Idx_reserve_ticket_id" ON "reserve" ("ticketId") `);
        await queryRunner.query(`DROP INDEX "Idx_reserve_user_ticket"`);
        await queryRunner.query(`DROP INDEX "Idx_reserve_ticket_id"`);
        await queryRunner.query(`CREATE TABLE "order" ("id" varchar PRIMARY KEY NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "status" text NOT NULL DEFAULT ('pending'), "totalAmount" integer, "userId" varchar)`);
        await queryRunner.query(`CREATE INDEX "Idx_order_user" ON "order" ("userId") `);
        await queryRunner.query(`DROP INDEX "Idx_reserve_status"`);
        await queryRunner.query(`CREATE TABLE "temporary_reserve" ("id" varchar PRIMARY KEY NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "status" text NOT NULL DEFAULT ('pending'), "expiresAt" datetime NOT NULL, "userId" varchar, CONSTRAINT "FK_dc318c87bc1d6552424a88a6444" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_reserve"("id", "createdAt", "updatedAt", "status", "expiresAt", "userId") SELECT "id", "createdAt", "updatedAt", "status", "expiresAt", "userId" FROM "reserve"`);
        await queryRunner.query(`DROP TABLE "reserve"`);
        await queryRunner.query(`ALTER TABLE "temporary_reserve" RENAME TO "reserve"`);
        await queryRunner.query(`CREATE INDEX "Idx_reserve_status" ON "reserve" ("status", "expiresAt") WHERE status = 'pending'`);
        await queryRunner.query(`DROP INDEX "Idx_reserve_status"`);
        await queryRunner.query(`CREATE TABLE "temporary_reserve" ("id" varchar PRIMARY KEY NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "status" text NOT NULL DEFAULT ('pending'), "expiresAt" datetime NOT NULL, "userId" varchar, "seatNumber" text NOT NULL, "concertId" varchar, "ticketTierId" varchar, "orderId" varchar, CONSTRAINT "FK_dc318c87bc1d6552424a88a6444" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_reserve"("id", "createdAt", "updatedAt", "status", "expiresAt", "userId") SELECT "id", "createdAt", "updatedAt", "status", "expiresAt", "userId" FROM "reserve"`);
        await queryRunner.query(`DROP TABLE "reserve"`);
        await queryRunner.query(`ALTER TABLE "temporary_reserve" RENAME TO "reserve"`);
        await queryRunner.query(`CREATE INDEX "Idx_reserve_status" ON "reserve" ("status", "expiresAt") WHERE status = 'pending'`);
        await queryRunner.query(`DROP INDEX "Idx_ticket_concert_user"`);
        await queryRunner.query(`DROP INDEX "Idx_sold_tickets"`);
        await queryRunner.query(`DROP INDEX "Idx_ticket_user_id"`);
        await queryRunner.query(`CREATE TABLE "temporary_ticket" ("id" varchar PRIMARY KEY NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "seatNumber" integer NOT NULL, "status" text NOT NULL DEFAULT ('available'), "pricePaid" integer, "concertId" varchar, "userId" varchar, "ticketTierId" varchar, "orderId" varchar, CONSTRAINT "Uq_ticket_concert_seat" UNIQUE ("concertId", "seatNumber"), CONSTRAINT "FK_40b8eb9e527f653c163bd00a231" FOREIGN KEY ("ticketTierId") REFERENCES "ticket_tier" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_0e01a7c92f008418bad6bad5919" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_ef8e1c3effd13564a3e3dd569ac" FOREIGN KEY ("concertId") REFERENCES "concert" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_ticket"("id", "createdAt", "updatedAt", "seatNumber", "status", "pricePaid", "concertId", "userId", "ticketTierId") SELECT "id", "createdAt", "updatedAt", "seatNumber", "status", "pricePaid", "concertId", "userId", "ticketTierId" FROM "ticket"`);
        await queryRunner.query(`DROP TABLE "ticket"`);
        await queryRunner.query(`ALTER TABLE "temporary_ticket" RENAME TO "ticket"`);
        await queryRunner.query(`CREATE INDEX "Idx_ticket_concert_user" ON "ticket" ("concertId", "userId") `);
        await queryRunner.query(`CREATE INDEX "Idx_sold_tickets" ON "ticket" ("status", "concertId", "ticketTierId") WHERE status = 'sold'`);
        await queryRunner.query(`CREATE INDEX "Idx_ticket_user_id" ON "ticket" ("userId") `);
        await queryRunner.query(`DROP INDEX "Idx_sold_tickets"`);
        await queryRunner.query(`DROP INDEX "Idx_ticket_concert_user"`);
        await queryRunner.query(`DROP INDEX "Idx_ticket_user_id"`);
        await queryRunner.query(`CREATE TABLE "temporary_ticket" ("id" varchar PRIMARY KEY NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "seatNumber" integer NOT NULL, "status" text NOT NULL DEFAULT ('available'), "pricePaid" integer, "concertId" varchar, "userId" varchar, "ticketTierId" varchar, "orderId" varchar, CONSTRAINT "FK_40b8eb9e527f653c163bd00a231" FOREIGN KEY ("ticketTierId") REFERENCES "ticket_tier" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_0e01a7c92f008418bad6bad5919" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_ef8e1c3effd13564a3e3dd569ac" FOREIGN KEY ("concertId") REFERENCES "concert" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_ticket"("id", "createdAt", "updatedAt", "seatNumber", "status", "pricePaid", "concertId", "userId", "ticketTierId", "orderId") SELECT "id", "createdAt", "updatedAt", "seatNumber", "status", "pricePaid", "concertId", "userId", "ticketTierId", "orderId" FROM "ticket"`);
        await queryRunner.query(`DROP TABLE "ticket"`);
        await queryRunner.query(`ALTER TABLE "temporary_ticket" RENAME TO "ticket"`);
        await queryRunner.query(`CREATE INDEX "Idx_ticket_concert_user" ON "ticket" ("concertId", "userId") `);
        await queryRunner.query(`CREATE INDEX "Idx_ticket_user_id" ON "ticket" ("userId") `);
        await queryRunner.query(`DROP INDEX "Idx_ticket_concert_user"`);
        await queryRunner.query(`DROP INDEX "Idx_ticket_user_id"`);
        await queryRunner.query(`CREATE TABLE "temporary_ticket" ("id" varchar PRIMARY KEY NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "seatNumber" text NOT NULL, "status" text NOT NULL, "pricePaid" integer, "concertId" varchar, "userId" varchar, "ticketTierId" varchar, "orderId" varchar, CONSTRAINT "FK_40b8eb9e527f653c163bd00a231" FOREIGN KEY ("ticketTierId") REFERENCES "ticket_tier" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_0e01a7c92f008418bad6bad5919" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_ef8e1c3effd13564a3e3dd569ac" FOREIGN KEY ("concertId") REFERENCES "concert" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_ticket"("id", "createdAt", "updatedAt", "seatNumber", "status", "pricePaid", "concertId", "userId", "ticketTierId", "orderId") SELECT "id", "createdAt", "updatedAt", "seatNumber", "status", "pricePaid", "concertId", "userId", "ticketTierId", "orderId" FROM "ticket"`);
        await queryRunner.query(`DROP TABLE "ticket"`);
        await queryRunner.query(`ALTER TABLE "temporary_ticket" RENAME TO "ticket"`);
        await queryRunner.query(`CREATE INDEX "Idx_ticket_concert_user" ON "ticket" ("concertId", "userId") `);
        await queryRunner.query(`CREATE INDEX "Idx_ticket_user_id" ON "ticket" ("userId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "Uqi_reserve_concert_seat" ON "reserve" ("concertId", "seatNumber") WHERE status = 'pending'`);
        await queryRunner.query(`CREATE INDEX "Idx_sold_tickets" ON "ticket" ("status", "concertId", "ticketTierId") WHERE status = 'sold'`);
        await queryRunner.query(`DROP INDEX "Idx_ticket_concert_user"`);
        await queryRunner.query(`DROP INDEX "Idx_ticket_user_id"`);
        await queryRunner.query(`DROP INDEX "Idx_sold_tickets"`);
        await queryRunner.query(`CREATE TABLE "temporary_ticket" ("id" varchar PRIMARY KEY NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "seatNumber" text NOT NULL, "status" text NOT NULL, "pricePaid" integer, "concertId" varchar, "userId" varchar, "ticketTierId" varchar, "orderId" varchar, CONSTRAINT "Uq_ticket_concert_seat" UNIQUE ("concertId", "seatNumber"), CONSTRAINT "FK_40b8eb9e527f653c163bd00a231" FOREIGN KEY ("ticketTierId") REFERENCES "ticket_tier" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_0e01a7c92f008418bad6bad5919" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_ef8e1c3effd13564a3e3dd569ac" FOREIGN KEY ("concertId") REFERENCES "concert" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_ticket"("id", "createdAt", "updatedAt", "seatNumber", "status", "pricePaid", "concertId", "userId", "ticketTierId", "orderId") SELECT "id", "createdAt", "updatedAt", "seatNumber", "status", "pricePaid", "concertId", "userId", "ticketTierId", "orderId" FROM "ticket"`);
        await queryRunner.query(`DROP TABLE "ticket"`);
        await queryRunner.query(`ALTER TABLE "temporary_ticket" RENAME TO "ticket"`);
        await queryRunner.query(`CREATE INDEX "Idx_ticket_concert_user" ON "ticket" ("concertId", "userId") `);
        await queryRunner.query(`CREATE INDEX "Idx_ticket_user_id" ON "ticket" ("userId") `);
        await queryRunner.query(`CREATE INDEX "Idx_sold_tickets" ON "ticket" ("status", "concertId", "ticketTierId") WHERE status = 'sold'`);
        await queryRunner.query(`DROP INDEX "Idx_reserve_status"`);
        await queryRunner.query(`DROP INDEX "Uqi_reserve_concert_seat"`);
        await queryRunner.query(`CREATE TABLE "temporary_reserve" ("id" varchar PRIMARY KEY NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "status" text NOT NULL DEFAULT ('pending'), "expiresAt" datetime NOT NULL, "userId" varchar, "seatNumber" text NOT NULL, "concertId" varchar, "ticketTierId" varchar, "orderId" varchar, CONSTRAINT "FK_dc318c87bc1d6552424a88a6444" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_a3c7f5e645255435f49bf1302e2" FOREIGN KEY ("concertId") REFERENCES "concert" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_d1fbf4fb794eeef0c517f7a068d" FOREIGN KEY ("ticketTierId") REFERENCES "ticket_tier" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_06acfce86b754f3d225d161bfd7" FOREIGN KEY ("orderId") REFERENCES "order" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_reserve"("id", "createdAt", "updatedAt", "status", "expiresAt", "userId", "seatNumber", "concertId", "ticketTierId", "orderId") SELECT "id", "createdAt", "updatedAt", "status", "expiresAt", "userId", "seatNumber", "concertId", "ticketTierId", "orderId" FROM "reserve"`);
        await queryRunner.query(`DROP TABLE "reserve"`);
        await queryRunner.query(`ALTER TABLE "temporary_reserve" RENAME TO "reserve"`);
        await queryRunner.query(`CREATE INDEX "Idx_reserve_status" ON "reserve" ("status", "expiresAt") WHERE status = 'pending'`);
        await queryRunner.query(`CREATE UNIQUE INDEX "Uqi_reserve_concert_seat" ON "reserve" ("concertId", "seatNumber") WHERE status = 'pending'`);
        await queryRunner.query(`DROP INDEX "Idx_order_user"`);
        await queryRunner.query(`CREATE TABLE "temporary_order" ("id" varchar PRIMARY KEY NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "status" text NOT NULL DEFAULT ('pending'), "totalAmount" integer, "userId" varchar, CONSTRAINT "FK_caabe91507b3379c7ba73637b84" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_order"("id", "createdAt", "updatedAt", "status", "totalAmount", "userId") SELECT "id", "createdAt", "updatedAt", "status", "totalAmount", "userId" FROM "order"`);
        await queryRunner.query(`DROP TABLE "order"`);
        await queryRunner.query(`ALTER TABLE "temporary_order" RENAME TO "order"`);
        await queryRunner.query(`CREATE INDEX "Idx_order_user" ON "order" ("userId") `);
        await queryRunner.query(`DROP INDEX "Idx_ticket_concert_user"`);
        await queryRunner.query(`DROP INDEX "Idx_ticket_user_id"`);
        await queryRunner.query(`DROP INDEX "Idx_sold_tickets"`);
        await queryRunner.query(`CREATE TABLE "temporary_ticket" ("id" varchar PRIMARY KEY NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "seatNumber" text NOT NULL, "status" text NOT NULL, "pricePaid" integer, "concertId" varchar, "userId" varchar, "ticketTierId" varchar, "orderId" varchar, CONSTRAINT "Uq_ticket_concert_seat" UNIQUE ("concertId", "seatNumber"), CONSTRAINT "FK_40b8eb9e527f653c163bd00a231" FOREIGN KEY ("ticketTierId") REFERENCES "ticket_tier" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_0e01a7c92f008418bad6bad5919" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_ef8e1c3effd13564a3e3dd569ac" FOREIGN KEY ("concertId") REFERENCES "concert" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_8f4c2f0a2877e526e8881b51464" FOREIGN KEY ("orderId") REFERENCES "order" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_ticket"("id", "createdAt", "updatedAt", "seatNumber", "status", "pricePaid", "concertId", "userId", "ticketTierId", "orderId") SELECT "id", "createdAt", "updatedAt", "seatNumber", "status", "pricePaid", "concertId", "userId", "ticketTierId", "orderId" FROM "ticket"`);
        await queryRunner.query(`DROP TABLE "ticket"`);
        await queryRunner.query(`ALTER TABLE "temporary_ticket" RENAME TO "ticket"`);
        await queryRunner.query(`CREATE INDEX "Idx_ticket_concert_user" ON "ticket" ("concertId", "userId") `);
        await queryRunner.query(`CREATE INDEX "Idx_ticket_user_id" ON "ticket" ("userId") `);
        await queryRunner.query(`CREATE INDEX "Idx_sold_tickets" ON "ticket" ("status", "concertId", "ticketTierId") WHERE status = 'sold'`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "Idx_sold_tickets"`);
        await queryRunner.query(`DROP INDEX "Idx_ticket_user_id"`);
        await queryRunner.query(`DROP INDEX "Idx_ticket_concert_user"`);
        await queryRunner.query(`ALTER TABLE "ticket" RENAME TO "temporary_ticket"`);
        await queryRunner.query(`CREATE TABLE "ticket" ("id" varchar PRIMARY KEY NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "seatNumber" text NOT NULL, "status" text NOT NULL, "pricePaid" integer, "concertId" varchar, "userId" varchar, "ticketTierId" varchar, "orderId" varchar, CONSTRAINT "Uq_ticket_concert_seat" UNIQUE ("concertId", "seatNumber"), CONSTRAINT "FK_40b8eb9e527f653c163bd00a231" FOREIGN KEY ("ticketTierId") REFERENCES "ticket_tier" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_0e01a7c92f008418bad6bad5919" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_ef8e1c3effd13564a3e3dd569ac" FOREIGN KEY ("concertId") REFERENCES "concert" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "ticket"("id", "createdAt", "updatedAt", "seatNumber", "status", "pricePaid", "concertId", "userId", "ticketTierId", "orderId") SELECT "id", "createdAt", "updatedAt", "seatNumber", "status", "pricePaid", "concertId", "userId", "ticketTierId", "orderId" FROM "temporary_ticket"`);
        await queryRunner.query(`DROP TABLE "temporary_ticket"`);
        await queryRunner.query(`CREATE INDEX "Idx_sold_tickets" ON "ticket" ("status", "concertId", "ticketTierId") WHERE status = 'sold'`);
        await queryRunner.query(`CREATE INDEX "Idx_ticket_user_id" ON "ticket" ("userId") `);
        await queryRunner.query(`CREATE INDEX "Idx_ticket_concert_user" ON "ticket" ("concertId", "userId") `);
        await queryRunner.query(`DROP INDEX "Idx_order_user"`);
        await queryRunner.query(`ALTER TABLE "order" RENAME TO "temporary_order"`);
        await queryRunner.query(`CREATE TABLE "order" ("id" varchar PRIMARY KEY NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "status" text NOT NULL DEFAULT ('pending'), "totalAmount" integer, "userId" varchar)`);
        await queryRunner.query(`INSERT INTO "order"("id", "createdAt", "updatedAt", "status", "totalAmount", "userId") SELECT "id", "createdAt", "updatedAt", "status", "totalAmount", "userId" FROM "temporary_order"`);
        await queryRunner.query(`DROP TABLE "temporary_order"`);
        await queryRunner.query(`CREATE INDEX "Idx_order_user" ON "order" ("userId") `);
        await queryRunner.query(`DROP INDEX "Uqi_reserve_concert_seat"`);
        await queryRunner.query(`DROP INDEX "Idx_reserve_status"`);
        await queryRunner.query(`ALTER TABLE "reserve" RENAME TO "temporary_reserve"`);
        await queryRunner.query(`CREATE TABLE "reserve" ("id" varchar PRIMARY KEY NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "status" text NOT NULL DEFAULT ('pending'), "expiresAt" datetime NOT NULL, "userId" varchar, "seatNumber" text NOT NULL, "concertId" varchar, "ticketTierId" varchar, "orderId" varchar, CONSTRAINT "FK_dc318c87bc1d6552424a88a6444" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "reserve"("id", "createdAt", "updatedAt", "status", "expiresAt", "userId", "seatNumber", "concertId", "ticketTierId", "orderId") SELECT "id", "createdAt", "updatedAt", "status", "expiresAt", "userId", "seatNumber", "concertId", "ticketTierId", "orderId" FROM "temporary_reserve"`);
        await queryRunner.query(`DROP TABLE "temporary_reserve"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "Uqi_reserve_concert_seat" ON "reserve" ("concertId", "seatNumber") WHERE status = 'pending'`);
        await queryRunner.query(`CREATE INDEX "Idx_reserve_status" ON "reserve" ("status", "expiresAt") WHERE status = 'pending'`);
        await queryRunner.query(`DROP INDEX "Idx_sold_tickets"`);
        await queryRunner.query(`DROP INDEX "Idx_ticket_user_id"`);
        await queryRunner.query(`DROP INDEX "Idx_ticket_concert_user"`);
        await queryRunner.query(`ALTER TABLE "ticket" RENAME TO "temporary_ticket"`);
        await queryRunner.query(`CREATE TABLE "ticket" ("id" varchar PRIMARY KEY NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "seatNumber" text NOT NULL, "status" text NOT NULL, "pricePaid" integer, "concertId" varchar, "userId" varchar, "ticketTierId" varchar, "orderId" varchar, CONSTRAINT "FK_40b8eb9e527f653c163bd00a231" FOREIGN KEY ("ticketTierId") REFERENCES "ticket_tier" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_0e01a7c92f008418bad6bad5919" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_ef8e1c3effd13564a3e3dd569ac" FOREIGN KEY ("concertId") REFERENCES "concert" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "ticket"("id", "createdAt", "updatedAt", "seatNumber", "status", "pricePaid", "concertId", "userId", "ticketTierId", "orderId") SELECT "id", "createdAt", "updatedAt", "seatNumber", "status", "pricePaid", "concertId", "userId", "ticketTierId", "orderId" FROM "temporary_ticket"`);
        await queryRunner.query(`DROP TABLE "temporary_ticket"`);
        await queryRunner.query(`CREATE INDEX "Idx_sold_tickets" ON "ticket" ("status", "concertId", "ticketTierId") WHERE status = 'sold'`);
        await queryRunner.query(`CREATE INDEX "Idx_ticket_user_id" ON "ticket" ("userId") `);
        await queryRunner.query(`CREATE INDEX "Idx_ticket_concert_user" ON "ticket" ("concertId", "userId") `);
        await queryRunner.query(`DROP INDEX "Idx_sold_tickets"`);
        await queryRunner.query(`DROP INDEX "Uqi_reserve_concert_seat"`);
        await queryRunner.query(`DROP INDEX "Idx_ticket_user_id"`);
        await queryRunner.query(`DROP INDEX "Idx_ticket_concert_user"`);
        await queryRunner.query(`ALTER TABLE "ticket" RENAME TO "temporary_ticket"`);
        await queryRunner.query(`CREATE TABLE "ticket" ("id" varchar PRIMARY KEY NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "seatNumber" integer NOT NULL, "status" text NOT NULL DEFAULT ('available'), "pricePaid" integer, "concertId" varchar, "userId" varchar, "ticketTierId" varchar, "orderId" varchar, CONSTRAINT "FK_40b8eb9e527f653c163bd00a231" FOREIGN KEY ("ticketTierId") REFERENCES "ticket_tier" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_0e01a7c92f008418bad6bad5919" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_ef8e1c3effd13564a3e3dd569ac" FOREIGN KEY ("concertId") REFERENCES "concert" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "ticket"("id", "createdAt", "updatedAt", "seatNumber", "status", "pricePaid", "concertId", "userId", "ticketTierId", "orderId") SELECT "id", "createdAt", "updatedAt", "seatNumber", "status", "pricePaid", "concertId", "userId", "ticketTierId", "orderId" FROM "temporary_ticket"`);
        await queryRunner.query(`DROP TABLE "temporary_ticket"`);
        await queryRunner.query(`CREATE INDEX "Idx_ticket_user_id" ON "ticket" ("userId") `);
        await queryRunner.query(`CREATE INDEX "Idx_ticket_concert_user" ON "ticket" ("concertId", "userId") `);
        await queryRunner.query(`DROP INDEX "Idx_ticket_user_id"`);
        await queryRunner.query(`DROP INDEX "Idx_ticket_concert_user"`);
        await queryRunner.query(`ALTER TABLE "ticket" RENAME TO "temporary_ticket"`);
        await queryRunner.query(`CREATE TABLE "ticket" ("id" varchar PRIMARY KEY NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "seatNumber" integer NOT NULL, "status" text NOT NULL DEFAULT ('available'), "pricePaid" integer, "concertId" varchar, "userId" varchar, "ticketTierId" varchar, "orderId" varchar, CONSTRAINT "Uq_ticket_concert_seat" UNIQUE ("concertId", "seatNumber"), CONSTRAINT "FK_40b8eb9e527f653c163bd00a231" FOREIGN KEY ("ticketTierId") REFERENCES "ticket_tier" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_0e01a7c92f008418bad6bad5919" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_ef8e1c3effd13564a3e3dd569ac" FOREIGN KEY ("concertId") REFERENCES "concert" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "ticket"("id", "createdAt", "updatedAt", "seatNumber", "status", "pricePaid", "concertId", "userId", "ticketTierId", "orderId") SELECT "id", "createdAt", "updatedAt", "seatNumber", "status", "pricePaid", "concertId", "userId", "ticketTierId", "orderId" FROM "temporary_ticket"`);
        await queryRunner.query(`DROP TABLE "temporary_ticket"`);
        await queryRunner.query(`CREATE INDEX "Idx_ticket_user_id" ON "ticket" ("userId") `);
        await queryRunner.query(`CREATE INDEX "Idx_ticket_concert_user" ON "ticket" ("concertId", "userId") `);
        await queryRunner.query(`CREATE INDEX "Idx_sold_tickets" ON "ticket" ("status", "concertId", "ticketTierId") WHERE status = 'sold'`);
        await queryRunner.query(`DROP INDEX "Idx_ticket_user_id"`);
        await queryRunner.query(`DROP INDEX "Idx_sold_tickets"`);
        await queryRunner.query(`DROP INDEX "Idx_ticket_concert_user"`);
        await queryRunner.query(`ALTER TABLE "ticket" RENAME TO "temporary_ticket"`);
        await queryRunner.query(`CREATE TABLE "ticket" ("id" varchar PRIMARY KEY NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "seatNumber" integer NOT NULL, "status" text NOT NULL DEFAULT ('available'), "pricePaid" integer, "concertId" varchar, "userId" varchar, "ticketTierId" varchar, CONSTRAINT "Uq_ticket_concert_seat" UNIQUE ("concertId", "seatNumber"), CONSTRAINT "FK_40b8eb9e527f653c163bd00a231" FOREIGN KEY ("ticketTierId") REFERENCES "ticket_tier" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_0e01a7c92f008418bad6bad5919" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_ef8e1c3effd13564a3e3dd569ac" FOREIGN KEY ("concertId") REFERENCES "concert" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "ticket"("id", "createdAt", "updatedAt", "seatNumber", "status", "pricePaid", "concertId", "userId", "ticketTierId") SELECT "id", "createdAt", "updatedAt", "seatNumber", "status", "pricePaid", "concertId", "userId", "ticketTierId" FROM "temporary_ticket"`);
        await queryRunner.query(`DROP TABLE "temporary_ticket"`);
        await queryRunner.query(`CREATE INDEX "Idx_ticket_user_id" ON "ticket" ("userId") `);
        await queryRunner.query(`CREATE INDEX "Idx_sold_tickets" ON "ticket" ("status", "concertId", "ticketTierId") WHERE status = 'sold'`);
        await queryRunner.query(`CREATE INDEX "Idx_ticket_concert_user" ON "ticket" ("concertId", "userId") `);
        await queryRunner.query(`DROP INDEX "Idx_reserve_status"`);
        await queryRunner.query(`ALTER TABLE "reserve" RENAME TO "temporary_reserve"`);
        await queryRunner.query(`CREATE TABLE "reserve" ("id" varchar PRIMARY KEY NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "status" text NOT NULL DEFAULT ('pending'), "expiresAt" datetime NOT NULL, "userId" varchar, CONSTRAINT "FK_dc318c87bc1d6552424a88a6444" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "reserve"("id", "createdAt", "updatedAt", "status", "expiresAt", "userId") SELECT "id", "createdAt", "updatedAt", "status", "expiresAt", "userId" FROM "temporary_reserve"`);
        await queryRunner.query(`DROP TABLE "temporary_reserve"`);
        await queryRunner.query(`CREATE INDEX "Idx_reserve_status" ON "reserve" ("status", "expiresAt") WHERE status = 'pending'`);
        await queryRunner.query(`DROP INDEX "Idx_reserve_status"`);
        await queryRunner.query(`ALTER TABLE "reserve" RENAME TO "temporary_reserve"`);
        await queryRunner.query(`CREATE TABLE "reserve" ("id" varchar PRIMARY KEY NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "status" text NOT NULL DEFAULT ('pending'), "expiresAt" datetime NOT NULL, "userId" varchar, "ticketId" varchar, CONSTRAINT "FK_dc318c87bc1d6552424a88a6444" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "reserve"("id", "createdAt", "updatedAt", "status", "expiresAt", "userId") SELECT "id", "createdAt", "updatedAt", "status", "expiresAt", "userId" FROM "temporary_reserve"`);
        await queryRunner.query(`DROP TABLE "temporary_reserve"`);
        await queryRunner.query(`CREATE INDEX "Idx_reserve_status" ON "reserve" ("status", "expiresAt") WHERE status = 'pending'`);
        await queryRunner.query(`DROP INDEX "Idx_order_user"`);
        await queryRunner.query(`DROP TABLE "order"`);
        await queryRunner.query(`CREATE INDEX "Idx_reserve_ticket_id" ON "reserve" ("ticketId") `);
        await queryRunner.query(`CREATE INDEX "Idx_reserve_user_ticket" ON "reserve" ("userId", "ticketId") WHERE status = 'pending'`);
        await queryRunner.query(`DROP INDEX "Idx_reserve_ticket_id"`);
        await queryRunner.query(`DROP INDEX "Idx_reserve_user_ticket"`);
        await queryRunner.query(`DROP INDEX "Idx_reserve_status"`);
        await queryRunner.query(`ALTER TABLE "reserve" RENAME TO "temporary_reserve"`);
        await queryRunner.query(`CREATE TABLE "reserve" ("id" varchar PRIMARY KEY NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "status" text NOT NULL DEFAULT ('pending'), "expiresAt" datetime NOT NULL, "userId" varchar, "ticketId" varchar, CONSTRAINT "FK_4b0d1ff7d8b0498c45e47f47538" FOREIGN KEY ("ticketId") REFERENCES "ticket" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_dc318c87bc1d6552424a88a6444" FOREIGN KEY ("userId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "reserve"("id", "createdAt", "updatedAt", "status", "expiresAt", "userId", "ticketId") SELECT "id", "createdAt", "updatedAt", "status", "expiresAt", "userId", "ticketId" FROM "temporary_reserve"`);
        await queryRunner.query(`DROP TABLE "temporary_reserve"`);
        await queryRunner.query(`CREATE INDEX "Idx_reserve_ticket_id" ON "reserve" ("ticketId") `);
        await queryRunner.query(`CREATE INDEX "Idx_reserve_user_ticket" ON "reserve" ("userId", "ticketId") WHERE status = 'pending'`);
        await queryRunner.query(`CREATE INDEX "Idx_reserve_status" ON "reserve" ("status", "expiresAt") WHERE status = 'pending'`);
    }

}
